<!--
  BugReportModal.svelte

  Cmd+Alt+B opens this from anywhere. User types what went wrong; we
  auto-prefill the current URL, browser, build version, and any crashes
  the client-side crash-reporter recorded in the last few minutes. On
  submit we open the GitHub "new issue" page in a new tab with the body
  already filled in, so the user can review + click Submit without
  having to remember where to go.

  Why not direct POST to GitHub? Two reasons:
    1. GitHub's issues API needs user-scope OAuth; we'd have to broker
       per-user tokens. The prefill-URL trick side-steps that entirely
       and still lands the user at exactly one click away from submit.
    2. It makes clear to the user that the report is leaving their
       self-hosted Nexus. Self-hosters dislike silent phone-home.
-->
<script lang="ts">
	import { X } from 'lucide-svelte';
	import { page } from '$app/stores';
	import { getRecentCrashes } from '$lib/client/bug-report-context';

	interface Props {
		open: boolean;
		buildVersion?: string;
		onclose: () => void;
	}

	let { open = $bindable(false), buildVersion = 'dev', onclose }: Props = $props();

	const GH_ISSUE_URL = 'https://github.com/PetalCat/Nexus/issues/new';

	let description = $state('');
	let includeCrashes = $state(true);
	let textareaEl: HTMLTextAreaElement | null = $state(null);

	// Focus on open so the user can just start typing.
	$effect(() => {
		if (open && textareaEl) {
			queueMicrotask(() => textareaEl?.focus());
		}
	});

	function escapeTitle(s: string): string {
		// GitHub issue title param; 256-char cap keeps URL sane.
		return s.replace(/\s+/g, ' ').trim().slice(0, 80) || 'Bug report';
	}

	function buildBody(): string {
		const url = typeof location !== 'undefined' ? location.href : '(unknown)';
		const ua = typeof navigator !== 'undefined' ? navigator.userAgent : '(unknown)';
		const routeId = $page.route?.id ?? '(unknown)';
		const crashes = includeCrashes ? getRecentCrashes() : [];

		const crashSection =
			crashes.length === 0
				? ''
				: '\n\n## Recent JS errors (last 5 min)\n\n' +
					crashes
						.map(
							(c) =>
								`- **${c.message}** (${c.surface ?? 'n/a'}) @ ${new Date(c.at).toISOString()}` +
								(c.stack ? `\n  <details><summary>stack</summary>\n\n\`\`\`\n${c.stack}\n\`\`\`\n\n  </details>` : '')
						)
						.join('\n');

		return [
			'## What happened',
			description.trim() || '_(user did not fill this in)_',
			'',
			'## Page',
			`- URL: ${url}`,
			`- Route: \`${routeId}\``,
			'',
			'## Environment',
			`- Nexus build: \`${buildVersion}\``,
			`- User agent: ${ua}`,
			crashSection,
			'',
			'---',
			'_Generated by the Cmd+Alt+B in-app bug reporter._'
		].join('\n');
	}

	function submit() {
		const title = escapeTitle(description);
		const body = buildBody();
		const qs = new URLSearchParams({
			title,
			body,
			labels: 'bug,in-app-report'
		});
		window.open(`${GH_ISSUE_URL}?${qs.toString()}`, '_blank', 'noopener');
		// Reset + close so the next Cmd+Alt+B starts fresh.
		description = '';
		onclose();
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			e.preventDefault();
			onclose();
		}
		if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
			e.preventDefault();
			submit();
		}
	}
</script>

{#if open}
	<!-- svelte-ignore a11y_click_events_have_key_events -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="fixed inset-0 z-[200] flex items-start justify-center bg-black/60 backdrop-blur-sm p-6"
		onclick={onclose}
		onkeydown={handleKeydown}
	>
		<div
			class="mt-24 w-full max-w-xl bg-[var(--color-panel,#1a1a1d)] border border-[var(--color-border,#2a2a30)] rounded-xl shadow-2xl"
			role="dialog"
			aria-modal="true"
			aria-labelledby="bug-report-title"
			onclick={(e) => e.stopPropagation()}
			onkeydown={handleKeydown}
		>
			<div class="flex items-center justify-between p-4 border-b border-[var(--color-border,#2a2a30)]">
				<h2 id="bug-report-title" class="text-lg font-semibold">Report a bug</h2>
				<button
					class="p-1 rounded hover:bg-white/5 transition-colors"
					onclick={onclose}
					aria-label="Close"
				>
					<X size={18} />
				</button>
			</div>

			<div class="p-4 space-y-3">
				<p class="text-sm text-[var(--color-muted,#888)]">
					What went wrong? We'll open a prefilled GitHub issue with the page URL,
					your browser, and any JS errors we caught. You can edit before submitting.
				</p>

				<textarea
					bind:this={textareaEl}
					bind:value={description}
					class="w-full h-32 px-3 py-2 bg-black/20 border border-[var(--color-border,#2a2a30)] rounded-md text-sm resize-none focus:outline-none focus:border-[var(--color-accent,#4a9eff)]"
					placeholder="Describe what you were doing and what went wrong…"
				></textarea>

				<label class="flex items-center gap-2 text-sm">
					<input type="checkbox" bind:checked={includeCrashes} />
					Include recent JS errors in the report
				</label>

				<div class="flex justify-end gap-2 pt-2">
					<button
						class="px-3 py-1.5 text-sm rounded-md hover:bg-white/5 transition-colors"
						onclick={onclose}
					>
						Cancel
					</button>
					<button
						class="px-3 py-1.5 text-sm rounded-md bg-[var(--color-accent,#4a9eff)] text-white hover:opacity-90 transition-opacity disabled:opacity-50"
						onclick={submit}
						disabled={description.trim().length === 0}
					>
						Open GitHub Issue
					</button>
				</div>

				<p class="text-xs text-[var(--color-muted,#666)] pt-1">
					Shortcut: <kbd class="px-1 rounded bg-black/30">⌘</kbd>+<kbd class="px-1 rounded bg-black/30">⌥</kbd>+<kbd class="px-1 rounded bg-black/30">B</kbd>
					to open this from anywhere. <kbd class="px-1 rounded bg-black/30">⌘</kbd>+<kbd class="px-1 rounded bg-black/30">↵</kbd>
					to submit.
				</p>
			</div>
		</div>
	</div>
{/if}
